Movie_Rent/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Movie_Rent.Models;
using Movie_Rent.Dal;

namespace Movie_Rent.Controllers
{
    public class LoginController : Controller
    {// controller for our first page - login page

        public User GetUserByName(string userName)
        {//get the user with the userName if exist in our users db
            //connect to db
            UserDal dal = new UserDal();

            User u1 = (from u in dal.users
                          where u.UserName == userName
                          select u).FirstOrDefault();


            return u1;
        }

        public bool checkUserName (string userName)
        {//check if the user name exist in our users db
            //connect to db
            UserDal dal = new UserDal();

            bool check = (from u in dal.users
                          where u.UserName == userName
                          select u).Any();
            if (check)
            {
                return true;
            }


            return false;
        }

        public bool checkUserPassword(string userName, string userPassword)
        {//check if the user name exist in our users db and if it have the password  userPassword
            //connect to db
            UserDal dal = new UserDal();

            bool check = (from u in dal.users
                          where u.UserName == userName && u.Password == userPassword
                          select u).Any();
            if (check)
            {
                return true;
            }


            return false;
        }

        public ActionResult LoginPage(User u1)
        {//the form at our login page

            bool loginNameCheck = checkUserName(u1.UserName);

            if (loginNameCheck && u1.UserName!=null)
            {// chack if the name of the user exist in the db
                bool loginPasswordCheck = checkUserPassword(u1.UserName, u1.Password);
                if (loginPasswordCheck)
                {//check if the user enter the right password

                    //getting the user info from the db
                    User u2 = GetUserByName(u1.UserName);
                    //saving the user info we need for next actions
                    Session["UserType"] = u2.Type;
                    Session["UserName"] = u2.UserName;
                    return RedirectToAction("HomePage", "Home");
                }
                ViewBag.message2 = "The password is incorrect"; 

            }
            else if (u1.UserName != null) { ViewBag.message1 = "The user name not exist"; }
            else if (u1.UserName == null) { ViewBag.message1 = ""; ViewBag.message2 = ""; }

            return View(u1); 
        }

        public ActionResult RegistrationPage(User u1)
        {//the form at our registration page

            bool loginNameCheck = checkUserName(u1.UserName);

            if (ModelState.IsValid && !loginNameCheck)
            {
                //connect to db
                UserDal dal = new UserDal();
                dal.users.Add(u1);
                dal.SaveChanges();

                //saving the user info we need for next actions
                Session["UserType"] = "user";
                Session["UserName"] = u1.UserName;
                return RedirectToAction("HomePage", "Home");
            }
            else if (loginNameCheck) { ViewBag.message1 = "That user name already exist"; }
            return View(u1);
        }
    }
}

Movie_Rent/Controllers/ManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Movie_Rent.Models;
using Movie_Rent.Dal;


namespace Movie_Rent.Controllers
{
    public class ManagerController : Controller
    {
        // GET: Manager
        public ActionResult ManagerZonePage()
        {//take us to the manager zone Page view

            return View();
        }

        public ActionResult UsersListPage()
        {//take us to the users list page view

            //connect to db users
            UserDal dal = new UserDal();

            UserList list = new UserList();
            list.users= (from u in dal.users
                          select u).ToList<User>();

            return View(list);
        }


        public ActionResult RemoveUser(string UserName)
        {//remove the user with the same name in the db and return us to Users List Page

            //connect to db
            UserDal dal = new UserDal();

            //get the user from db
            User u1 = (from u in dal.users
                       where u.UserName == UserName
                       select u).FirstOrDefault();

            //remove the user from db
            dal.users.Remove(u1);
            dal.SaveChanges();

            return RedirectToAction("UsersListPage");
        }

        public bool checkUserName(string userName)
        {//check if the user name exist in our users db
            //connect to db
            UserDal dal = new UserDal();

            bool check = (from u in dal.users
                          where u.UserName == userName
                          select u).Any();

            return check;
        }

        public ActionResult AddUserPage(User u1)
        {//take us to the Add user page view

            bool NameCheck = checkUserName(u1.UserName);

            if (Request.Form["option"] == null)
            {
                ViewBag.message2 = "you diden't checked Manger/User option";
                return View(u1);
            }

            u1.Type = Request.Form["option"].ToString();

            if (ModelState.IsValid && !NameCheck)
            {
                //connect to db
                UserDal dal = new UserDal();
                dal.users.Add(u1);
                dal.SaveChanges();

                return RedirectToAction("ManagerZonePage");
            }
            else if (NameCheck) { ViewBag.message1 = "That user name already exist"; }
            return View(u1);
        }

        public ActionResult MovieListPage()
        {//take us to the movie list page view

            //connect to db movies
            MovieDal dal = new MovieDal();

            MovieList list = new MovieList();
            list.movies = (from m in dal.movies
                          select m).ToList<Movie>();

            return View(list);
        }

        public ActionResult RemoveMovie(string MovieName)
        {//remove the movie with the same name in the db and return us to Movie List Page

            //connect to db
            MovieDal dal = new MovieDal();

            //get the movie from db
            Movie m1 = (from m in dal.movies
                        where m.MovieName == MovieName
                        select m).FirstOrDefault();

            //remove the movie from db
            dal.movies.Remove(m1);
            dal.SaveChanges();

            return RedirectToAction("MovieListPage");
        }

        public ActionResult EditMovie(string MovieName)
        {//get the movie we want to add from db and send him to AddMoviePage

            //connect to db
            MovieDal dal = new MovieDal();

            //get the movie from db
            Movie m1 = (from m in dal.movies
                        where m.MovieName == MovieName
                        select m).FirstOrDefault();

            return View ("EditMoviePage", m1);
        }

        public ActionResult EditMoviePage(Movie m1)
        {//take us to the edit movie page view - in the edit action we need to chack only if ModelState.IsValid

            if (ModelState.IsValid)
            {
                //connect to db
                MovieDal dal = new MovieDal();

                //get the max value of OrderNum
                Movie m2 = (from m in dal.movies
                             where m.MovieName== m1.MovieName
                             select m).FirstOrDefault();

                //edit movie in db
                m2.MovieName = m1.MovieName;
                m2.Type= m1.Type;
                m2.Description = m1.Description;
                m2.Link = m1.Link;
                m2.ImageLink = m1.ImageLink;

                dal.SaveChanges();

                return RedirectToAction("MovieListPage");
            }

            return View(m1);

        }

        public bool checkMovieName(string MovieName)
        {//check if the movie name exist in our users db
            //connect to db
            MovieDal dal = new MovieDal();

            bool check = (from m in dal.movies
                          where m.MovieName == MovieName
                          select m).Any();

            return check;
        }

        public ActionResult AddMoviePage(Movie m1)
        {//take us to the add movie page view

            bool NameCheck = checkMovieName(m1.MovieName);

            if (ModelState.IsValid && !NameCheck)
            {
                //save date of creating the movie in ouer db
                m1.Date = DateTime.Now;

                //connect to db
                MovieDal dal = new MovieDal();
                dal.movies.Add(m1);
                dal.SaveChanges();

                return RedirectToAction("MovieListPage");
            }
            else if (NameCheck) { ViewBag.message1 = "That movie name already exist"; }
            return View(m1);
        }
        public ActionResult OrderListPage()
        {//take us to the order list page view

            //connect to db order
            OrderDal dal = new OrderDal();

            OrderList list = new OrderList();
            list.orders = (from o in dal.Orders
                           select o).ToList<Order>();

            return View(list);
        }
    }
}

Movie_Rent/Views/Shared/Home_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MoviesRent.com - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MoviesRent.com - Home Page", "HomePage", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Log Out", "LoginPage", "Login")</li>
                    <li>@Html.ActionLink("Orders", "OrdersPage", "Home")</li>
                    <li>@Html.ActionLink("Watch List", "WatchListPage", "Home")</li>

                        @if (Session["UserType"].ToString() == "manager")
                        {
                            <li>@Html.ActionLink("Manager Zone", "ManagerZonePage", "Manager")</li>
                        }

                    <li><span style="display:inline-block; width: 350px;"></span></li>
                    <li><a>Hello, @Session["UserName"]</a></li>
                </ul>
            </div>
        </div>  
    </div>
    <div class="container body-content">
        <div class="row">
            <div class="col-md-12">
                <img src="~/Content/images/mvc_logo.PNG" class="img-responsive center-block" />
            </div>
        </div>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - MoviesRent.com</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Movie_Rent/Views/Shared/Login_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MoviesRent - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<script src="~/Scripts/jquery-1.10.2.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

<body>
    <div>
        @Html.Partial("SiteLogo")
    </div>
    @RenderBody()
    <footer>
        <p>&copy; @DateTime.Now.Year - MoviesRent.com</p>
    </footer>
</body>
</html>

Movie_Rent/Views/Shared/MovieInfo.cshtml
@model Movie_Rent.Models.Movie

<table>
    <tr>
        <td style="color:darkcyan; font-size:larger "><strong>Category:</strong></td>
        <td style="color:black; font-size:large">
            <span style="display:inline-block; width: 5px;"></span>
            @Model.Type
        </td>
    </tr>
</table>

<br />
<center style="color:darkslategrey; font-size:larger">@Model.Description</center>
<br />
<center>
    <img src="@Model.ImageLink" style="vertical-align: middle; width: 200px;">
    <br />
</center>

Movie_Rent/Views/Shared/SiteLogo.cshtml
<div class="row">
    <div class="col-md-12">
        <h2 style="text-align: center;">
            <img src="~/Content/images/mvc_logo.PNG" class="img-responsive center-block" />
        </h2>
</div>

Movie_Rent/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="row">
            <div class="col-md-12">
                <img src="~/Content/images/mvc_logo.PNG" class="img-responsive center-block" />
            </div>
        </div>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>